language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - rainzha@163.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: gCzBtdpM3ruKEKylUflU+RjpFOFyoUTAkAlIXMMrHG+yu+GgYuacM9U+1Kc+o81qTV/xHahJ33Ic07UqaBFAAwZDYbt5xsz7p7e+hvr5RwfKDk55ExPCmugujiwUaeIquap2XCpKZ1f8K6MtkL6ygD7BRWgetRgFd4eSCsWbo4Bw43IVlDsUrNYvQazcmoWR+rmq6aDrONes3Uz6Y/o2dgSek3sXGD/n/R1lCg2+5Vhh7zLx/KRoX2pogDUq8iTU71HJDFvyewu4wHyUWCYvHFJI9rumhDLlH8Cw7aO8WcGrxcwnoL191PnSNyueZmpw9jFjh1cnoGpXgEBQ/qWaXB/hS7GdOtJU8NT+ycyCfOLoGObOD6LQiyaeNHkKl94HvYwq+5w7wFPUB5on2m7p29dAs/rXvGXUwxz5614+0Y89CRannwu5pYtLGLHIFs0yT5+TZ481kXRMka1X/YrVNu5Z95ihgmnVyQvXXmnjrMrKUDE/9dGpFQrBPapLlwUTb59lxqCdHPFFzWlwFSC9wm3dDiJ3GjAiTi8tI04dt+F1H9usmFfzc34NOIDMZ9Zb6Bz3bj1ENnlYe3j6oK9MGUuKXLgLFpf+jdc3/yRJdA/K8TzgGm0MLNV1PZ90bCoyXuekt1xrX4Iuo2BtNWLMObRlzwOu8bk/18jsRasLLtg=
  - secure: pFbQvds8i5IuJWsifld/c8xWztJBMWcWg6b4/FBjiOMfst9BhQi+uEV46EFs6Tl7V2d7n0hs5YHUW0t8vmtuPjg/gCfhBW6KI5rqkLlaJidDaJP3wI7B8Muyf0v1GzkPBOu8kqO2pw8VXHwHbtBgQTAdF2i+TitcCkN7M9ZBC2RwZ670lnkXDXUTLewUeaxTemqx2jCWmrTYAoNVwQa7Nko/faJUSS9WCSVRw6+twomqzmx7f8sqDDFHrzfGpEoXhsAALyusCpSu7dwmyjoMJvrHwglK9J9hPT6Yp4skl5j7joVyqDVdVi32piIJSqqJHKaxuExYwScZg0kybakI4vbDeW7ZxxVBdcYm7zhaHk0Y/xhw922BX/S1gx+R7PQ1ijNiyI0ojW0no3k7k2Yo5jxFGTS4Vn+/5d42j2Rh2ydDkbF7j41B+kKBQWwqoopWes1mHiFcUgCwrCiCu8Vs9ql7s4AhmJxY1qfgEdGdxTWn+Ongh8jAcFxFYkg1coeE08XXVCYpfoPXosooOr5h67B2mcu1TUU1Le7PigGyIxXn9yfkIROSfLnBwZMe1FOaXCTQCaivwkdU3856wmVSu+6aSHYe0rQWFxHW0L+RJzPgNGHTbS8c1nA8/U2sq55axT7CEle1stpjFUWiOLKCxAeu5bIUeXw/B8Uhmck/Noo=
  matrix:
  - SPIMA_SIMPLESERVICE_DOCKER_IMAGE=rainzha/spima-simpleservice:latest
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- gradle build docker
- docker push $SPIMA_SIMPLESERVICE_DOCKER_IMAGE
