language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - rainzha@163.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  matrix:
  - SPIMA_SIMPLESERVICE_DOCKER_IMAGE=rainzha/spima-simpleservice:latest
  global:
  - secure: u+WjoKh9fXh5ojQ2ywXHzaazdON+26loGDf20SXZ1ASN9JXEfnETRqc23j0n+82ldRCnvYpKjU1MHqf8DrEVxr+nuCdIe2plWt4LlSQ+jK6MJ0O/Y0Vn5FfSbAO4saobC21s/zAZ3ZauEqJQde3prPaovSsf2nZxsED/EKGZoFR2qlg+nZ3kGoc9VzKVE275alr+suM1v902ZUtzKtwSfQxZYdo17bVvnWxF2LvBs6F/DJEHHVbTLExkx476O+Wz9CFZQwk2SoMVgRH+e7yQN81i45oiAHE/6s1joHr0RV2udQevMMNsaSnCvQEyYbFyLOHL8ZB8vcAPSwJytQqGDsJNIAmr9lowBdy8uTEDe+QGy2alzKPm3a0W3dPflPT5f+LEGLI6430C/T5D0VNeZmTIHaF2zWX1OvuUBCs3J0U6sE5RK0sVBVfiuI+xSKsi0i+B+If30J/fgbMoMnlpa5OAU40udZSwtTckpKwbQTy8HPRfjzgIJT2rDCCPEe6trQPIwxWyiTpXWYqXf8zDjIARvIPqheB0fJIl7meBk30+kYk12ssTN5KkuMggWGn8WZPNgh2B6wBTx9LAZRVpp5ofeNXLZ5nhTic2/9TqmfuV6STSdkQJF80M8ZIF3qDo2jopuO0U0XnYQgVBerls+3fHB2v2etqH0fFZ8uDnZxY=
  - secure: Liq360mpHIgk6sV64JU7VgQKliSpE7sm7I9h8Z3Di8lnWoaGV0jooCTuJSwdQYKJSYOnwxZ8djUUMxtQ5wJHF8UkQCYHtXTU/bhhGvUPQaR35sHzXwyoBcM8bNkhaHC+keVfdm+b6+RXA/Acza2Itg4Y85xWrFMsj7pnDqKwU6dPZVLB8+h99G9Ed+ptCejqMS3rt5KkBblo/LbEwfjqqOp/6trp3dy1BViI1v9mmyytqMY5P2rLT6lx3YjT/SZh+G0gBYMwyt+nKfzegNKDJLeru/PGs0zQzSic8WHbnZ3UWm4mElIrI87cstbDbHQU+JBY2LxfEiG4oeivefRyPegTteNOy2Km0pDFORWSqdDRqXnmR8TC/Ze9shjazvNgMIhAQrj2T9dgl3eBw0C6Kvq+C9o4qMpUW8syg8pqmEoIdj9bGViWmgHdM1yBgeA35nL57NyjKrFTSkwftHpcb0i4PkJi+N0cjY610gfdQc1rpDMgZR1Aco6x9fDqNxSZOEwDXORC7tCy1PqX0PLEqgVC7tJZViUPO4kSGaTCxJiWTJo9O+LWmfEJ2jbe7LYRkGo6kNx3UsB5sKv6zgqi4ZedBxhJb4bNzNI4KxZ7wu+UDnCNXIhKeZhhm/d9JhbHbdxq+vNVXgL+Sn4v9AnCzmGyBZvqIBgc2NxQIPCkywI=
script:
- gradle build docker
- bash travis_scripts/docker_push
