language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - rainzha@163.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
 matrix:
  - SPIMA_SIMPLESERVICE_DOCKER_IMAGE=rainzha/spima-simpleservice
script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - gradle build docker
  - docker push $SPIMA_SIMPLESERVICE_DOCKER_IMAGE
